name: Deploy NestJS to Render
run-name: deploy-backend-to-render
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    with:
      node-version: '22'
      test-cmd: 'npm run test:cov'
      continue-on-error: true

  staging-deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
