name: Deploy NestJS to Render
run-name: deploy-backend-to-render
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    with:
      node-version: '22'
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Deploy application
        run: |
          echo "Deploying the application..."
