export enum Environment {
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_EXTRA_AUTH_SOURCE = 'DB_EXTRA_AUTH_SOURCE',
  DB_EXTRA_SSL = 'DB_EXTRA_SSL',
  DB_EXTRA_QUERY = 'DB_EXTRA_QUERY',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  CACHE_MANAGER_TTL = 'CACHE_MANAGER_TTL',
  ENDPOINT_SECRET_KEY = 'ENDPOINT_SECRET_KEY',
  TOKEN_SIGN_EXPIRATION_TIME = 'TOKEN_SIGN_EXPIRATION_TIME',
}

export enum NodeEnv {
  PRODUCTION = 'production',
  DEVELOPMENT = 'development',
}
